spring:
  application:
    name: collabtasker-backend
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    format:
      date-time: iso
  security:
    user:
      password: Test12345_
