name: Backend Format

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - backend/**
  schedule:
    - cron: '28 5 * * 6'

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --aosp"
          skip-commit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code
