name: Backend Format

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  pull_request:
    types:
      - opened
  schedule:
    - cron: '28 5 * * 6'

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"
